t Fix Unity builds of FmtAsDefaultTests.cpp
The #define of APPROVAL_TESTS_DEFAULT_STREAM_CONVERTER needs to be
present in main.cpp.

Error output began with:

In file included from ....ApprovalTests.cpp/examples/fmt_approvals_demo/FmtAsDefaultTests.cpp:6:
....ApprovalTests.cpp/examples/fmt_approvals_demo/FmtAsDefault.h:4:9: warning: 'APPROVAL_TESTS_DEFAULT_STREAM_CONVERTER' macro redefined [-Wmacro-redefined]
#define APPROVAL_TESTS_DEFAULT_STREAM_CONVERTER FmtToString
        ^
../../ApprovalTests/../ApprovalTests/namers/../Approvals.h:346:9: note: previous definition is here
#define APPROVAL_TESTS_DEFAULT_STREAM_CONVERTER StringMaker
        ^
In file included from examples/fmt_approvals_demo/CMakeFiles/fmt_approvals_demo.dir/Unity/unity_0.cxx:3:
In file included from ....ApprovalTests.cpp/examples/fmt_approvals_demo/main.cpp:5:
In file included from ../../ApprovalTests/ApprovalTests.hpp:16:
../../ApprovalTests/utilities/StringMaker.h:14:15: error: invalid operands to binary expression ('std::stringstream' (aka 'basic_stringstream<char>') and 'const std::__1::vector<int, std::__1::allocator<int> >')
            s << contents;
            ~ ^  ~~~~~~~~
../../ApprovalTests/../ApprovalTests/namers/../Approvals.h:67:60: note: in instantiation of function template specialization 'ApprovalTests::StringMaker::toString<std::__1::vector<int, std::__1::allocator<int> > >' requested here
            verify(TCompileTimeOptions::ToStringConverter::toString(contents), options);
                                                           ^
....ApprovalTests.cpp/examples/fmt_approvals_demo/FmtAsDefaultTests.cpp:14:16: note: in instantiation of function template specialization 'ApprovalTests::TApprovals<ApprovalTests::ToStringCompileTimeOptions<ApprovalTests::StringMaker> >::verify<std::__1::vector<int, std::__1::allocator<int> >, int>' requested here
    Approvals::verify(numbers);
               ^
/opt/local/libexec/llvm-9.0/bin/../include/c++/v1/ostream:219:20: note: candidate function not viable: no known conversion from 'const std::__1::vector<int, std::__1::allocator<int> >' to 'const void *' for 1st argument; take the address of the argument with &
    basic_ostream& operator<<(const void* __p);
                   ^
.....