F Remove mingw getenv_s() declaration workaround
It's no longer needed, and is giving:

D:/a/ApprovalTests.cpp/ApprovalTests.cpp/ApprovalTests/utilities/WinMinGWUtils.h:15:13:
error: 'errno_t getenv_s(size_t*, char*, size_t, const char*)' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
   15 |     errno_t getenv_s(size_t* ret_required_buf_size,
      |             ^~~~~~~~