t Fmt tests moved to new example program fmt_approvals_demo
This is to start fixing the Unity builds, which started
failing once FmtApprovals.h and FmtToString.h were added
to ApprovalTests.hpp during the creation of the v.8.8.0
release...

The error was
  Building CXX object tests/DocTest_Tests/CMakeFiles/DocTest_Tests.dir/Unity/unity_0_cxx.cxx.o
  In file included from ..../tests/DocTest_Tests/CMakeFiles/DocTest_Tests.dir/Unity/unity_0_cxx.cxx:22:
 .../tests/DocTest_Tests/integrations/FmtTests.cpp:18:5: error: use of undeclared identifier 'FmtApprovals'; did you mean 'Approvals'?

In one the Unity builds, ApprovalTests.hpp was getting
read before FmtTests.cpp was loaded - meaning that FmtApprovals
was never seen.