Revert "e   Make doc/requirements.txt consistent with current Read the Docs config"
This reverts commit 1b90a0c8 - which ironically caused the Read the Docs
build to dail with exactly the problem that I have been trying
to fix on my Mac:

Converting all .md files to .rst...
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/breathe/__init__.py", line 1, in <module>
    from . import directives
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/breathe/directives.py", line 1, in <module>
    from breathe.directive.base import create_warning
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/breathe/directive/base.py", line 8, in <module>
    from breathe.renderer.sphinxrenderer import SphinxRenderer
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 97, in <module>
    class CStructObject(BaseObject, c.CStructObject):
AttributeError: module 'sphinx.domains.c' has no attribute 'CStructObject'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/approvaltestscpp/envs/latest/lib/python3.7/site-packages/breathe/renderer/sphinxrenderer.py", line 97, in <module>
    class CStructObject(BaseObject, c.CStructObject):
AttributeError: module 'sphinx.domains.c' has no attribute 'CStructObject'
The full traceback has been saved in /tmp/sphinx-err-gp30ry77.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>.